local data_util = require("__Krastorio2-spaced-out__.data-util")

data_util.add_prerequisite("biolab", "agricultural-science-pack")
data_util.add_prerequisite("overgrowth-soil", "agricultural-science-pack")
data_util.add_prerequisite("overgrowth-soil", "agricultural-science-pack")
data_util.add_prerequisite("production-science-pack", "advanced-material-processing")
data_util.add_prerequisite("spidertron", "fission-reactor-equipment")
data_util.add_prerequisite("fission-reactor-equipment", "electromagnetic-science-pack")
data_util.add_prerequisite("kr-quarry-mineral-extraction", "recycling")

data_util.remove_prerequisite("biolab", "biter-egg-handling")
data_util.remove_prerequisite("biolab", "uranium-processing")
data_util.remove_prerequisite("productivity-module-3", "biter-egg-handling")
data_util.remove_prerequisite("overgrowth-soil", "biter-egg-handling")
data_util.remove_prerequisite("kr-biter-virus", "biter-egg-handling")
data_util.remove_prerequisite("promethium-science-pack", "biter-egg-handling")
data_util.remove_prerequisite("kr-antimatter-reactor", "kr-fusion-energy")
data_util.remove_prerequisite("production-science-pack", "uranium-processing")
data_util.remove_prerequisite("fission-reactor-equipment", "nuclear-power")
data_util.remove_prerequisite("planet-discovery-aquilo", "planet-discovery-nauvis")
data_util.remove_prerequisite("uranium-mining", "planet-discovery-nauvis")
data_util.remove_prerequisite("spidertron", "kr-fusion-reactor-equipment")
data_util.remove_prerequisite("kr-quarry-mineral-extraction", "electric-engine")

data_util.add_recipe_unlock("biochamber", "kr-water-mineralization")
data_util.add_recipe_unlock("kr-quarry-mineral-extraction", "kr-quarry-drill")
data_util.add_recipe_unlock("fusion-reactor", "kr-fusion-reactor")
data_util.add_recipe_unlock("fusion-reactor", "kr-advanced-steam-turbine")
